# Generated by Django 5.2.6 on 2025-11-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "url",
                    models.CharField(
                        default="https://exemplo.com/produto-indefinido", max_length=600
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=800)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.TextField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="siteweb.loja"
                    ),
                ),
            ],
        ),
    ]
