# Generated by Django 5.2.6 on 2025-11-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="url",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="loja",
            name="url",
            field=models.CharField(
                default="https://exemplo.com/produto-indefinido", max_length=600
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=600),
        ),
    ]
