# Generated by Django 5.2.6 on 2025-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0002_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="frete",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="prazo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
