# Generated by Django 5.2.6 on 2025-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0002_produto_imagem_produto_url_alter_loja_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=700),
        ),
    ]
