# Generated by Django 5.2.8 on 2025-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0003_produto_frete_produto_prazo"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="codigoProduto",
            field=models.CharField(default=0, max_length=400),
        ),
    ]
