# Generated by Django 5.2.6 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0003_alter_produto_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=800),
        ),
    ]
