# Generated by Django 5.2.8 on 2025-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0004_produto_codigoproduto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.CharField(max_length=20),
        ),
    ]
